### ISSUE TITLE
OOM Error

### ISSUE THREAD

**Issue by vellrya** [steelkiwi/cropiwa#19]
На многих устройствах при попытке выделить большУю часть изображения приложение падает:
### Caused by: java.lang.OutOfMemoryError
                                                                         at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                         at android.graphics.Bitmap.createBitmap(Bitmap.java:640)
                                                                         at android.graphics.Bitmap.createBitmap(Bitmap.java:575)
                                                                         at android.graphics.Bitmap.createBitmap(Bitmap.java:501)
                                                                         at com.steelkiwi.cropiwa.image.CropArea.applyCropTo(CropArea.java:35)
                                                                         at com.steelkiwi.cropiwa.image.CropImageTask.doInBackground(CropImageTask.java:49)
                                                                         at com.steelkiwi.cropiwa.image.CropImageTask.doInBackground(CropImageTask.java:20)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                                         at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
                                                                         at java.lang.Thread.run(Thread.java:856) 
Хотелось бы исправления)

**Comment by polyak01** [comment]
@vellrya сейчас дико загружены. Займёмся фиксами в ближайшее время.

**Comment by flasher297** [comment]
I've also faced this issue, but on next line of code
immutableCropped.copy(immutableCropped.getConfig(), true);  - CropArea.java - 40th line of code.

**Comment by flasher297** [comment]
I've created PR that fixes this issue.
https://github.com/steelkiwi/cropiwa/pull/35
Please read its description.

**Comment by romshiri** [comment]
Any news?

**Comment by KennyGoers** [comment]
I'm running into this myself, any other attempt to deal with it? Project dead?
