### ISSUE TITLE
Fatal Exception if cropping while holding image out of bounds

### ISSUE THREAD

**Issue by NicolasDucom** [steelkiwi/cropiwa#41]
I've noticed an issue (fringe case honestly) when cropping an image while holding it out of the canvas's bounds : [Screenshot here](https://ibb.co/f8u8Mw) 
Here's the error I get :

`E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                                                     Process: myApp, PID: 14146
                                                                     java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:762)
                                                                      Caused by: java.lang.IllegalArgumentException: y must be >= 0
                                                                         at android.graphics.Bitmap.checkXYSign(Bitmap.java:423)
                                                                         at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
                                                                         at android.graphics.Bitmap.createBitmap(Bitmap.java:793)
                                                                         at com.steelkiwi.cropiwa.image.CropArea.applyCropTo(CropArea.java:35)
                                                                         at com.steelkiwi.cropiwa.image.CropImageTask.doInBackground(CropImageTask.java:49)
                                                                         at com.steelkiwi.cropiwa.image.CropImageTask.doInBackground(CropImageTask.java:20)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                         at java.lang.Thread.run(Thread.java:762) `

I haven't created a pull request to fix the problem because I don't know which solution you prefer, maybe just trigger the ErrorListener ?
Thanks :)

**Comment by NicolasDucom** [comment]
Sorry, Hadn't noticed #11
