### ISSUE TITLE
crop some gif picture crash 

### ISSUE THREAD

**Issue by neo1201** [steelkiwi/cropiwa#42]
the bellow picture always crash 

![786c66a35feff245bc6b1278b8d50e5b](https://user-images.githubusercontent.com/5358278/36021394-9bbdb64c-0dc0-11e8-8538-43790b6b840c.gif)

```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #7
                                                                      Process: com.yitantech.gaigai, PID: 31754
                                                                      java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Bitmap$Config.nativeInt' on a null object reference
                                                                          at android.graphics.Bitmap.copy(Bitmap.java:569)
                                                                          at com.steelkiwi.cropiwa.image.CropArea.applyCropTo(CropArea.java:40)
                                                                          at com.steelkiwi.cropiwa.image.CropImageTask.doInBackground(CropImageTask.java:49)
                                                                          at com.steelkiwi.cropiwa.image.CropImageTask.doInBackground(CropImageTask.java:20)
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                          at java.lang.Thread.run(Thread.java:818) 
02-09 17:27:54.930 32618-32618/com.yitantech.gaigai E/ActivityThread: Failed to find provider info for com.tinker.debug.debugprovider
```

**Comment by neo1201** [comment]
Could I catch this exception prevent crash ?
