### ISSUE TITLE
crash with cropiwa while cropping image

### ISSUE THREAD

**Issue by lkasdolka** [steelkiwi/cropiwa#49]
stacktrace as follows:

java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:325)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:760)
java.lang.IllegalArgumentException: x must be >= 0
at android.graphics.Bitmap.checkXYSign(Bitmap.java:406
at android.graphics.Bitmap.createBitmap(Bitmap.java:742)
at android.graphics.Bitmap.createBitmap(Bitmap.java:712)
at com.android.maya.business.shoot.cropiwa.image.CropArea.create(CropArea.java)
moveRectToCoordinateSystem(CropArea.java)
applyCropTo(CropArea.java)
findRealCoordinate(CropArea.java)
at com.android.maya.business.shoot.cropiwa.image.CropImageTask.doInBackground(CropImageTask.java)
onPostExecute(CropImageTask.java)
at com.android.maya.business.shoot.cropiwa.image.CropImageTask.doInBackground(CropImageTask.java)
at android.os.AsyncTask$2.call(AsyncTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 morejava.lang.IllegalArgumentException: x must be >= 0
at android.graphics.Bitmap.checkXYSign(Bitmap.java:406)
at android.graphics.Bitmap.createBitmap(Bitmap.java:742)
at android.graphics.Bitmap.createBitmap(Bitmap.java:712)
at com.android.maya.business.shoot.cropiwa.image.CropArea.create(CropArea.java)
moveRectToCoordinateSystem(CropArea.java)
applyCropTo(CropArea.java)
findRealCoordinate(CropArea.java)
at com.android.maya.business.shoot.cropiwa.image.CropImageTask.doInBackground(CropImageTask.java)
onPostExecute(CropImageTask.java)
at com.android.maya.business.shoot.cropiwa.image.CropImageTask.doInBackground(CropImageTask.java)
at android.os.AsyncTask$2.call(AsyncTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:760)

**Comment by BlackDizel** [comment]
same crash. cropiwa settings
```
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            app:ci_aspect_ratio_h="4"
            app:ci_aspect_ratio_w="3"
            app:ci_border_color="@color/colorAccentGreen"
            app:ci_border_width="4dp"
            app:ci_crop_scale="0.85"
            app:ci_crop_shape="rectangle"
            app:ci_draw_grid="false"
            app:ci_dynamic_aspect_ratio="false"
            app:ci_scale_enabled="true"
            app:ci_translation_enabled="true"
```
reproducing by swipe image out of crop rectangle and press crop button by other finger at same time

**Comment by osamamohsen** [comment]
3274-4121 E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: grand.app.moonshop, PID: 3274
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference

**Comment by DeepakPanchariya** [comment]
cropView.setImageUri(imageUri)
setImageUri first and then run the code it will work

**Comment by FelipeGAlmeida** [comment]
I run into the same issue.

Also reproducing by swiping image out of crop circle and press crop button by other finger at same time.

Any updates about this?
